### ISSUE TITLE
cfssl can be installed with homebrew on OSX

### ISSUE THREAD

**Issue by tonybecker** [kelseyhightower/kubernetes-the-hard-way#14]
Are you wanting to have this repository transform eventually into an automated tool, or recommend ways to make it easier?  Because installing CFSSL on OS X can be done with:

`brew install cfssl`

**Comment by kelseyhightower** [comment]
@tonybecker This is great feedback, but I'm not sure if I want to capture all those details in this repository . I want people to take a single path and focus on learning, but I do want to improve the guide for as many people as possible.

I think fetching the binaries is a good default for learning out of the box. While I'm going to close this issue, I'm going to continue to think about ideas like this going forward.

Thanks for taking the time to file this issue.

**Comment by willthames** [comment]
I came from the new docs to suggest something similar. My thoughts are that this would be "If you have brew installed, you can run `brew install cfssl`. Otherwise, here are the steps for installing from scratch". This simplifies the instructions for those with brew, without needing to explain how to setup brew for those who don't.
