### ISSUE TITLE
cannot kubectl exec into pods (1.6 with TLS bootstrapping)

### ISSUE THREAD

**Issue by kornface13** [kelseyhightower/kubernetes-the-hard-way#159]
When using the RBAC setup and TLS bootstrapping with 1.6, you cannot use kubectl exec to get a CLI on a pod.  For example:

The certificate is issued to the hostname rather than the FQDN.  So I see this error:
`Error from server: error dialing backend: dial tcp: lookup ubuntu-minion02 on 192.168.10.1:53: no such host.`

That makes sense...its missing the DNS suffix and my client isn't using the same suffix as the node.  The FQDN is ubuntu-minion02.lab.net

When I put a hostname override into the kubelet config it results in this error:
`Error from server: error dialing backend: x509: certificate is valid for system:node:ubuntu-minion01.lab.net, not ubuntu-minion01.lab.net`

So the cert appears to be missing the FQDN of the node by default, and even if you use hostname-override, the RBAC attributes are prepended on the hostname, which breaks PKI.
  
Is this easily fixable?  Server version 1.6.1.  Kubectl version 1.6.0-rc.1.

**Comment by mkorejo** [comment]
I noticed a similar message trying to deploy the DNS cluster add-on and it turns out there is some fundamental TLS authentication issue here. I can't even create a simple deployment with a single container. Regardless of where the pod gets placed I see a message like this using `kubectl logs`:

`Error from server: Get https://kube-worker2:10250/containerLogs/kube-system/kube-dns-v20-c6lhf/kubedns: x509: certificate is valid for system:node:kube-worker2, not kube-worker2`

`Error from server: Get https://kube-worker1:10250/containerLogs/default/mongo-deployment-638052851-23b6x/mongo: x509: certificate is valid for system:node:kube-worker1, not kube-worker1`

**Comment by mkorejo** [comment]
The solution is to generate an additional TLS server certificate and associated key signed by the CA, distribute these to the worker nodes, then modify the unit file for the kubelet on each worker to point to these.

First, create a `kubelet-csr.json` along with existing `kubernetes-csr.json` in Lab 2:
```
{
  "CN": "kubelet",
  "hosts": [
    "10.32.0.1",
    "10.240.0.20",
    "10.240.0.21",
    "10.240.0.22",
    "130.211.170.40",
    "127.0.0.1",
    "kube-worker0",
    "kube-worker1",
    "kube-worker2",
    "kubernetes.default"
  ],
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names": [
    {
      "C": "US",
      "L": "Portland",
      "O": "Kubernetes",
      "OU": "Cluster",
      "ST": "Oregon"
    }
  ]
}
```

Generate certificate and key:
`cfssl gencert -ca=pem/ca.pem -ca-key=pem/ca-key.pem -config=json/ca-config.json -profile=kubernetes json/kubelet-csr.json | cfssljson -bare kubelet`

Results in:
```
kubelet.pem
kubelet-key.pem
```

Distribute certificate and key to workers:
`for host in kube-worker0 kube-worker1 kube-worker2; do gcloud compute copy-files pem/kubelet.pem pem/kubelet-key.pem ${host}:~/; done`

On each worker:
```
sudo systemctl stop kubelet
sudo mv kubelet.pem kubelet-key.pem /var/lib/kubelet/
sudo vi /etc/systemd/system/kubelet.service
```
and edit values for `tls-cert-file` and `tls-private-key-file` to point to `/var/lib/kubelet/kubelet.pem` and `/var/lib/kubelet/kubelet-key.pem` respectively.

Then:
```
sudo systemctl daemon-reload
sudo systemctl start kubelet
sudo systemctl status kubelet --no-pager
```

**Comment by kgrvamsi** [comment]
@kelseyhightower The above process of kubelet key generation in the authorization doc is missing.

**Comment by cypherfox** [comment]
The above process should not need to be in segment 02, as the bootstrap mechanism will create the certs automatically, but unfortunateley it currently does so with an insufficient list of identities in the cert.

Unfortunately the above does not work straight out of the box either, as the CN ('kubelet') is not accepted by the RBAC of the api servers, blocking access to registration.

**Comment by cypherfox** [comment]
The following csr seems to work for me (replace NODE_FQDN with the FQDN of each individual node).
You need to create a separate cert for each node.
```
{
  "CN": "system:node:${NODE_FQDN}",
  "hosts": [
    "10.32.0.1",
    "10.240.0.20",
    "10.240.0.21",
    "10.240.0.22",
    "130.211.170.40",
    "127.0.0.1",
    "kube-worker0",
    "kube-worker1",
    "kube-worker2",
    "kubernetes.default"
  ],
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names": [
    {
      "C": "US",
      "L": "Portland",
      "O": "system:nodes",
      "OU": "Cluster",
      "ST": "Oregon"
    }
  ]
}
```

**Comment by kgrvamsi** [comment]
@cypherfox Thanks for the prompt reply but i have some questions here with this process.

1)Consider i have 500 nodes to get auto register to the API server so do we need to generate for every server?
2)After all this process i still get this error "Unknown node name to register " after following all the steps.Is this area is a list of all servers and their hostname's to be here including master something like this
```
kubelet-cst.json

 "CN": "kubelet",
  "hosts": [
    "10.0.2.15",
    "192.168.1.107",
    "192.168.1.113",
    "192.168.1.111",
    "127.0.0.1",
    "slave_01",
    "slave_02",
    "kubernetes.default"
  ],

kubernetes-csr.json

"CN": "kubernetes",
  "hosts": [
    "10.0.2.15",
    "192.168.1.107",
    "192.168.1.113",
    "192.168.1.111",
    "127.0.0.1",
    "slave_01",
    "slave_02",
    "master",
    "kubernetes.default"
```
3)Can we run the cluster without the TLS keys or is this  manditory step to follow ?(knowing that the TLS will be a production way of implementing the Kubernetes cluster but to test if my cluster can come up without the TLS)?

**Comment by cypherfox** [comment]
Re 1) you don't. The feature is marked as experimental and is likely to improve. If you need this to work today you write a script that a) creates the apropriate cert, b) creates the apropriate config and c) pushes everything to the newly instanced node.

Re 2) You don't need the names of the clients in the kubernetes-csr, but otherwise, yes. To eliminate the exhaustive list see (Re 1).

If you do not need TLS, you can skip it. If you want to train yourself for implementing your production cluster, I would advise to slug it out with all the cert problems, since that what created a lot of small issues for me when setting up. And I would hope your production cluster will contain TLS. So you will have to master that learning curve. I guess KH called this "the hard way" for a reason.

Disclaimer: I am a very new desciple. My cluster is still not working to plan, I just found a way around the above problem. So please take my advice with a massive dose of salt.

**Comment by notxcain** [comment]
Do you know if this got fixed in 1.7, as TLS bootstrapping is on beta now?

**Comment by christianhuening** [comment]
@notxcain No it seemingly was not fixed in 1.7.2, as I just tried it out. Still getting the error ```certificate is valid for system:node:<nodename>, not for <nodename>```

**Comment by kelseyhightower** [comment]
This will be fixed in an upcoming update later next week.

**Comment by redbaron** [comment]
@kelseyhightower , could you please post a PR number for this fix?

**Comment by kelseyhightower** [comment]
I've updated all the docs. This should be fixed now.
