### ISSUE TITLE
kubectl get csr return with No Resource Found. 

### ISSUE THREAD

**Issue by sureshkrishnan83** [kelseyhightower/kubernetes-the-hard-way#172]
I am getting below error from controller01 
~$ kubectl get csr
No resources found.

The status for the kublet service shows that it is generating TLS cert but the controller is not receiving :( . 

kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2017-05-25 23:17:47 UTC; 16s ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 3005 (kubelet)
    Tasks: 6
   Memory: 9.7M
      CPU: 138ms
   CGroup: /system.slice/kubelet.service
           └─3005 /usr/bin/kubelet --api-servers=https://104.X.X.X:6433 --allow-privileged=true --cluster-dns=10.32.0.10 --cluster-domain=cluster.local --container-runtime=docker --experimental-boots

May 25 23:17:47 worker0 systemd[1]: Started Kubernetes Kubelet.
May 25 23:17:47 worker0 kubelet[3005]: Flag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
May 25 23:17:47 worker0 kubelet[3005]: I0525 23:17:47.626797    3005 feature_gate.go:144] feature gates: map[]
May 25 23:17:47 worker0 kubelet[3005]: I0525 23:17:47.627061    3005 bootstrap.go:58] Using bootstrap kubeconfig to generate TLS client cert, key and kubeconfig file

**Comment by moonek** [comment]
I have same problem, too

root@hardway-node:/etc/systemd/system# systemctl status kubelet --no-pager
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2017-05-30 04:39:26 UTC; 480ms ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
  Process: 2273 ExecStart=/usr/bin/kubelet --api-servers=https://172.28.128.41:6443 --allow-privileged=true --cluster-dns=10.32.0.10 --cluster-domain=cluster.local --container-runtime=docker --experimental-bootstrap-kubeconfig=/var/lib/kubelet/bootstrap.kubeconfig --network-plugin=kubenet --kubeconfig=/var/lib/kubelet/kubeconfig --serialize-image-pulls=false --register-node=true --tls-cert-file=/var/lib/kubelet/kubelet-client.crt --tls-private-key-file=/var/lib/kubelet/kubelet-client.key --cert-dir=/var/lib/kubelet --v=2 (code=exited, status=1/FAILURE)
 Main PID: 2273 (code=exited, status=1/FAILURE)

May 30 04:39:26 hardway-node systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
May 30 04:39:26 hardway-node systemd[1]: kubelet.service: Unit entered failed state.
May 30 04:39:26 hardway-node systemd[1]: kubelet.service: Failed with result 'exit-code'.

-------------------------------------------------------------------------------------------------------------------
root@hardway-node:/etc/systemd/system# journalctl -f -u kubelet
-- Logs begin at Tue 2017-05-30 04:36:09 UTC. --
May 30 04:40:34 hardway-node systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
May 30 04:40:34 hardway-node systemd[1]: Stopped Kubernetes Kubelet.
May 30 04:40:34 hardway-node systemd[1]: Started Kubernetes Kubelet.
May 30 04:40:34 hardway-node kubelet[2419]: Flag --api-servers has been deprecated, Use --kubeconfig instead. Will be removed in a future version.
May 30 04:40:34 hardway-node kubelet[2419]: I0530 04:40:34.243138    2419 feature_gate.go:144] feature gates: map[]
May 30 04:40:34 hardway-node kubelet[2419]: I0530 04:40:34.243383    2419 bootstrap.go:58] Using bootstrap kubeconfig to generate TLS client cert, key and kubeconfig file
May 30 04:40:34 hardway-node kubelet[2419]: error: failed to run Kubelet: cannot create certificate signing request: the server has asked for the client to provide credentials (post certificatesigningrequests.certificates.k8s.io)
May 30 04:40:34 hardway-node systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
May 30 04:40:34 hardway-node systemd[1]: kubelet.service: Unit entered failed state.
May 30 04:40:34 hardway-node systemd[1]: kubelet.service: Failed with result 'exit-code'.

----------------------------------------------------------------------------------------------------------------

root@hardway-master:~# kubectl get csr
No resources found.

**Comment by tevren** [comment]
Hi! Can you check that your firewall rules are correct?

**Comment by quangkeu** [comment]
Hi! What version of kubernetes did you use? Wondering why your api port is 6433?

**Comment by kelseyhightower** [comment]
I've updated all the docs. This should be fixed now.
