### ISSUE TITLE
Is it just me or there something missing with the 10.32.0.0/24 services network

### ISSUE THREAD

**Issue by wolfeidau** [kelseyhightower/kubernetes-the-hard-way#26]
Trying to figure out where this is routed?

I can only find it declared then used in the skydns pod, when i try deploy the pod i get.

```
$ kubectl create -f https://raw.githubusercontent.com/kelseyhightower/kubernetes-the-hard-way/master/skydns-svc.yaml
The Service "kube-dns" is invalid.
spec.clusterIP: Invalid value: "10.32.0.10": provided IP is not in the valid range
```

So close to having this working on AWS, just need to figure out this.

Cheers for your efforts so far!

**Comment by ae6rt** [comment]
That is weird, but Service IPs are not routed.  They are intercepted by iptables on the node and routed to the endpoint(s) where the Pod in question is actually running.

But as to why this address is out of range is odd, because the controller-manager provides a range in which this address resides:  https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-kubernetes-controller.md#kubernetes-controller-manager

Hmm.

**Comment by wolfeidau** [comment]
Thanks for the tip, this totally highlighted misconfiguration on my part.

I changed this in line with the underlying VPC range, once i put it back to the original range things now started working.

Cheers
