### ISSUE TITLE
Do I need a cri-containerd with CoreOS?

### ISSUE THREAD

**Issue by gavvvr** [kelseyhightower/kubernetes-the-hard-way#320]
Hello. Trying to follow your hard way, but stuck with installing `cri-containerd` on worker nodes.
The problem is that when I try to untar `cri-containerd-1.0.0-beta.1.linux-amd64.tar.gz` into root `/`, tar says:
> tar: ./usr/local/bin: Cannot utime: Read-only file system

From [SO](https://stackoverflow.com/a/37815119/3581539) I learned that `/usr` is read-only by design in CoreOS. Can I skip `cri-containerd` installation when using CoreOS for worker nodes? If not, how should I install it then?

**Comment by waynr** [comment]
> Can I skip cri-containerd installation when using CoreOS for worker nodes?

Yes, but you will have to modify the kubelet systemd service files to depend on docker instead. This is vaguely what my kubelet systemd service files look like:

```
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/kubernetes/kubernetes
After=docker.service
Requires=docker.service

[Service]
ExecStart=/home/core/usr/local/bin/kubelet \\
  --allow-privileged=true \\
  --anonymous-auth=false \\
  --authorization-mode=Webhook \\
  --client-ca-file=/var/lib/kubernetes/ca.pem \\
  --cloud-provider= \\
  --cluster-dns=10.32.0.10 \\
  --cluster-domain=cluster.local \\
  --container-runtime=remote \\
  --container-runtime-endpoint=unix:///var/run/docker.sock \\
  --image-pull-progress-deadline=2m \\
  --kubeconfig=/var/lib/kubelet/kubeconfig \\
  --network-plugin=cni \\
  --pod-cidr=${pod_cidr} \\
  --register-node=true \\
  --runtime-request-timeout=15m \\
  --tls-cert-file=/var/lib/kubelet/${instance}.pem \\
  --tls-private-key-file=/var/lib/kubelet/${instance}-key.pem \\
  --v=2
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```

The major difference here are the `Before` and `After` settings:

```
After=docker.service
Requires=docker.service
```

And the `--container-runtime-endpoint` setting:

```
  --container-runtime-endpoint=unix:///var/run/docker.sock \\
```

With this setup you should of course leave out the `cri-containerd` and `containerd` services when using `systemctl` to start up the `kubelet` and `kube-proxy` services.

**Comment by waynr** [comment]
By the way, in case it's not obvious I'm also using CoreOS instead of Ubuntu and I ran into the same problem you did. Another option if you still want to use `cri-containerd` is to unarchive the tarball in the `/home/core` directory using `tar -xvf cri-containerd-1.0.0-beta.1.linux-amd64.tar.gz -C /home/core`, then modify `/home/core/etc/systemd/system/containerd.service` and `/home/core/etc/systemd/system/cri-containerd.service` to point to the correct path for the `containerd` and `cri-containerd` binaries then copy them into `/etc/systemd/system`. There might be more than that to do but around that point in my analysis I figured it would be simpler just to go with docker so that's what I did.

**Comment by waynr** [comment]
UPDATE: I wrote my original comment prematurely, I still need to work out a couple bugs in my docker CRI setup to get kubelet working.

**Comment by gavvvr** [comment]
Hi and thank you for explanation and workarounds. I was wondering if this guide also misses `flannel` installation. Why? Or it is not required here for some reasons?

**Comment by kelseyhightower** [comment]
This guide is to provide one path for bootstrapping Kubernetes. Docker and flannel are not required my Kubernetes.
