### ISSUE TITLE
When are we supposed to install docker?

### ISSUE THREAD

**Issue by mlda065** [kelseyhightower/kubernetes-the-hard-way#372]
My understanding is that `Kubernetes = Docker + other stuff`. Isn't docker a dependency of the kubelet?

Why is it that when we install dependencies on the worker nodes (`09-bootstrapping-kubernetes-workers`) we don't also include docker?

> The following components will be installed on each node: runc, gVisor, container networking plugins, containerd, kubelet, and kube-proxy.

Is containerd an alternative to docker? I don't know what runc, gVisor and containerd are. (Yes I've already ~~googled~~ Ducked them, but I still don't understand)

Is `which docker` or `sudo which docker` supposed to work on the worker nodes?

**Comment by eosfor** [comment]
+1

**Comment by tfogo** [comment]
runc and containerd are components which were written and open-sourced by Docker. They are two of the underlying technologies that run Docker (since version 1.11).

runc is the component that actually runs containers. containerd is a daemon process which provides an API for running containers using runc. 

Kubernetes has something called the [Container Runtime Interface (CRI)](https://kubernetes.io/blog/2016/12/container-runtime-interface-cri-in-kubernetes/) which allows you to use any compatible runtime to run your containers. So Docker is not necessarily a dependency. You get to choose what runs your containers (and there are several options such as lxd, rkt, and cri-o). 

This tutorial is using the [cri-containerd plugin](https://kubernetes.io/blog/2017/11/containerd-container-runtime-options-kubernetes/) as the container runtime. Using containerd is more lightweight than using Docker and provides the same functionality (since Docker uses containerd under the hood anyway). 

You may have read that containerd or other runtimes are _OCI-compliant_. Docker and other large companies came together to decide on a standard for containers - how to define them and how to run them - this is the Open Container Initiative (OCI). If you use a different container runtime, as long as it's OCI-compliant you'll still be able to run Docker containers.

So you should think of Kubernetes more as "orchestration for _containers_". It often uses Docker (or its underlying technologies) but it doesn't have to. 

So `which docker` should not work.

You can think of gVisor as a layer that sandboxes containers from the underlying OS order to make containers safer. The "Why does gVisor exist" section of the docs offers a more in-depth answer: https://github.com/google/gvisor#why-does-gvisor-exist

Hope that's helpful. The container ecosystem is definitely tough to get to grips with!

**Comment by mlda065** [comment]
Thanks, that helps a lot.

I already read "why does gvisor exist". 

> gVisor implements Linux by way of Linux

doesn't really make any sense to me.

Your explanation makes sense.

Should we make a pull request to explain some of those things in this repo?
I'm halfway through the steps now, and I've found I'm learning less than I hoped.
This guide is more along the lines of 'here are the commands to do it', where I was hoping for 'here are the commands and an explanation of how each bit works'.

I suppose this is really an editorial decision. How much explanation should this guide include?

**Comment by rafaeltuelho** [comment]
@mlda065 I felt the same for a while, but then I noticed he references the official docs' topics covering the concept in each section. So if you stop a little to read the references briefly it should help ;-)

**Comment by kelseyhightower** [comment]
This guide leverages containerd for running containers. gVisor is an optional runtime for running untrusted workloads. Docker is no longer required to run containers under Kubernetes.
