### ISSUE TITLE
Add a logging lab

### ISSUE THREAD

**Issue by edevil** [kelseyhightower/kubernetes-the-hard-way#41]
I know that this guide is to setup a minimum working Kubernetes cluster but I feel that some information about sending logs to a centralized logging service would really help. There is a link to the official documentation about this subject but it revolves around specifying a flag at cluster creation and then some magic is supposed to happen in the background... Also, this would help people wanting to configure it for an existing cluster, instead of having to start over.

Maybe a lab on how to configure the cluster to send app and kube logs to an ELK cluster? ELK seems to be the most widely used solution along with fluentd.

Thanks.

**Comment by kelseyhightower** [comment]
This maybe the next lab that I work on, but I need to consider my bandwidth to keep such a lab up to date.

**Comment by zoidbergwill** [comment]
I remember struggling when trying to use the configs in the main repo to configure it on a GKE cluster that already existed, since some of the configs seemed to be missing.

https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch

I think the daemonset for fluentd was the main one I battled to find.

Maybe the documentation needs to improve in the main docs for logging with ELK?

**Comment by sandys** [comment]
the simpler version of logging is to enable docker logging to journald using "log-provider=journald"

**Comment by kelseyhightower** [comment]
After thinking about this again, I think logging is going to be out of scope for now. So many options out there that I'm afraid I won't have the bandwidth to pick a solution.
