### ISSUE TITLE
Please provide agnostic version - no gcloud

### ISSUE THREAD

**Issue by datascienceteam01** [kelseyhightower/kubernetes-the-hard-way#453]
Please provide a version to be run in a local vagrant, katacoda or any service  that doesn't require paid subscription unless you're specifically endorsed by google and/or working for them. In any other case, I see no reason to pay gcloud to learn kubernetes.

**Comment by bserdar** [comment]
I forked this repo a while ago to run it on VMs with Centos:

https://github.com/bserdar/kubernetes-the-hard-way

**Comment by maestrofx** [comment]
@datascienceteam01, you can run your clusters everywhere not tight to gcloud. In another case, you don't need to pay gcloud to learn Kubernetes because if it's gcloud-specific as this repo detail stated `Bootstrap Kubernetes the hard way on Google Cloud Platform` you can use your free trial account to play with it.
Just enjoy the great resources!

**Comment by ivamluz** [comment]
You can check a bare metal (that leverages Virtual Box VMs) here: https://github.com/mvallim/kubernetes-under-the-hood
