### ISSUE TITLE
GH Relative Links Broken

### ISSUE THREAD

**Issue by ronaldpetty** [kelseyhightower/kubernetes-the-hard-way#52]
Hello,

The links on the bottom of the page are not including the repo.

https://github.com/kelseyhightower/docs/10-cleanup.md

Should be:

https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/01-infrastructure.md

I have also seen

https://github.com/kelseyhightower/kubernetes-the-hard-way/docs/01-infrastructure.md

appear to work.  I suspect this is GH more than the MD.  For the record I am at Heathrow trying this.

Regards.

Ron

**Comment by yuvadm** [comment]
Same here, this looks like a Github bug, the syntax as used should work as expected.

**Comment by ronaldpetty** [comment]
Sent issue to GH.  Will report back if anything is found.

**Comment by kelseyhightower** [comment]
Thanks for reporting this. This looks like a GH bug. Should I not be using relative links?

**Comment by ronaldpetty** [comment]
I believe relative links are the way to go. I suspect they are broken at the moment.  I haven't heard back from GH.  The docs don't seem to be vary convincing on the topic though.

I would recommend linking to master for now, just to keep the ill informed from given up to easily on a broken link.

**Comment by venantius** [comment]
Your current usage of relative links only works if you're viewing README from the actual source tree, e.g. at https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/README.md rather than via the presentation of the README available at https://github.com/kelseyhightower/kubernetes-the-hard-way. Since there is no way to reconcile these two, I would recommend changing to use absolute links, which is what everybody else does to address this.

I hadn't really considered whether this was an issue with GitHub itself. I think it's a hard argument to make: it is reasonable to assume that "relative" links should always be rendered relative to the actual URL that they are loaded from; in this context there's essentially no way to reconcile the fact that the README is visible from different locations. This problem only really applies to the README, though, so I could see an argument for GitHub to deliberately construct links viewed from the basic project page differently.

**Comment by yuvadm** [comment]
@venantius that's not accurate, I have many repositories that use relative links in the README view and they render properly to the right link in the source tree

**Comment by codevbus** [comment]
Can confirm the links provided by @ronaldpetty work for me.

**Comment by kelseyhightower** [comment]
Fixed now!

**Comment by kelseyhightower** [comment]
Looks like this may have been a GH issues, but it's now resolved.
