### ISSUE TITLE
Is etcd supposed to be installed on the controllers?

### ISSUE THREAD

**Issue by jamescarr** [kelseyhightower/kubernetes-the-hard-way#92]
I noticed that from https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/03-etcd.md refers to controllerN vs. etcdN servers. Is this intentional?

The screenshot for https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/01-infrastructure-aws.md shows etcd running as separate servers.

**Comment by dewyatt** [comment]
I believe that's intentional. The lab states that etcd will be deployed on the controller nodes to save on resources (but recommends a separate cluster in production).

The screenshot is what makes it confusing and I hope it will be updated.

https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/03-etcd.md
> To limit the number of compute resource to complete this lab etcd is being installed on the Kubernetes controller nodes. In production environments etcd should be run on a dedicated set of machines for the following reasons:

**Comment by jamescarr** [comment]
Thanks. Yeah I figured that out and went with that setup in staging but the
screenshot really threw me off! :-)

**Comment by faizan82** [comment]
Oops! This was confusing. I opened a pr to change the doc.

**Comment by kelseyhightower** [comment]
Yes, I made the change to reduce the number of nodes required for the tutorial from 9 to 6.
